### ISSUE TITLE
Діалектиня?

### ISSUE THREAD

**Issue by pannakocka** [jellysquider/fem-bot#1]
I have problem with this tweet - https://twitter.com/feminitives_ua/status/930448517004279808
чому не 
Діалектик (від діалектика) «-»діалектикиня?
(пор. критик«-»критикиня)
Діалектиня виглядає утворенем від слова "діалект"
(даруйте, не знала, куди вам правильно написати і написала сюди)
ПС буду вдячна за математикиню, соціологиню і маркетологиню (якщо не було)

**Comment by jellysquider** [comment]
Дякую, слушне зауваження! Думаю, що це одрук - зараз виправлю і додам інші :)
